name: Deploy to Google Compute Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to Compute Engine
      run: |
        # SSH 키 설정
        echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > /tmp/private_key
        chmod 600 /tmp/private_key

        # Compute Engine 인스턴스에 접속하여 배포 스크립트 실행
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no username@34.168.69.149 'bash -s' < deploy_script.sh
