name: Deploy to Google App Engine

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 트리거됩니다.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        service_account_email: ${{ secrets.GCP_SA_EMAIL }}
        project_id: ${{ secrets.PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Set up environment variables
      run: |
        echo "MY_DB_USER=${{ secrets.GCP_SA_EMAIL }}" >> $GITHUB_ENV
        echo "MY_DATABASE=${{ secrets.MY_DATABASE }}" >> $GITHUB_ENV


   # Compute Engine에 배포하는 새로운 단계
    - name: Deploy to Compute Engine
      run: |
        # SSH 키 설정
        echo "${{ secrets.GCE_SSH_PRIVATE_KEY }}" > /tmp/private_key
        chmod 600 /tmp/private_key

        # Compute Engine 인스턴스에 접속하여 배포 스크립트 실행
        ssh -i /tmp/private_key -o StrictHostKeyChecking=no ${{ secrets.GCE_USER }}@${{ secrets.GCE_INSTANCE_IP }} 'bash -s' < deploy_script.sh
